# Generated by Django 2.0.6 on 2018-06-13 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='precio',
            field=models.PositiveIntegerField(default='0'),
        ),
    ]
